### ISSUE TITLE
Template provisioning failed, again

### ISSUE THREAD

**Issue by PYPsitehelp** [SharePoint/sp-provisioning-service#365]
**Describe the issue**
I tried to provision my team site, it failed. This happened to me several times my last site, and so I deleted that team and created a new one based on comments I received. I have not done anything in the new site.

**Expected behavior**
Provision the site.

**Screenshots**
<img width="910" alt="Screen Shot 2020-12-22 at 16 41 52" src="https://user-images.githubusercontent.com/74246896/102906238-a0d2d980-4474-11eb-986b-1573ae1738fc.png">

**Details (please complete the following information):**
- PnP Correlation ID:  54303520-eca5-4347-9b89-cc680744aeba !
--

- Reference Template: Staff home page https://lookbook.microsoft.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63

**Additional context**
This happened before with the old one I deleted and now it just keeps happening.
Is it possible my account restricts me? I am using my work email and wonder if that is an issue? Are the APIs working again? Is there anything else I can do?

Here are the old messages I received from Paolo with my last attempts with the old deleted team site:

_Unfortunately, it can be because of temporary hiccups in the APIs on the server side. Thanks for the update.

Thanks for trying again. In the log, we see the following exception: "Access denied. You do not have permission to perform this action or access this resource" while uploading a sample file (Updated Classroom Policies and Procedures.pptx) into a library. Could it be that you were already using/browsing the site before the end of the provisioning and, as such, the file was accidentally locked? Or could it be that you targeted the same site as before (the first try), and that file is somehow locked/checked-out? Please, let me know. I'll keep this item open in the meantime. Thanks._

**Comment by PaoloPia** [comment]
Hi @PYPsitehelp,
Thanks for trying again. Unfortunately, I keep on seeing the same issue in the log "Access denied. You do not have permission to perform this action or access this resource." for the file "Updated Classroom Policies and Procedures.pptx". Could you please try targeting a different site URL? Or deleting and re-creating the target site? Thanks.

**Comment by PYPsitehelp** [comment]
Hi @PaoloPia 
Thank you for your help.
I contacted my IT department at my school and they also tried with an Admin account and also failed.
We cannot find this document to delete it or change the access settings.
I am trying to do this again now and wil see the results. 
Thank you
Victoria

**Comment by PYPsitehelp** [comment]
Hello again @PaoloPia 
It failed again. Here is the link: Your request to provision
"Staff home page"
template failed!
Please report the issue here providing the following provisioning action correlation ID: 0bd9fa46-d25e-4af1-a7eb-b36643408660 !

Also, the IT manager tried with a global administrator account and it also failed. 
Is there anything we can do to get the site working?
Thank you!

**Comment by PaoloPia** [comment]
Hi,
I still see in the log the same exception, with the same file. I'm going to double-check the issue with the team that built the template. Stay tuned. Thanks.

**Comment by phipham95** [comment]
Having a similar problem provisioning M365 Learning Pathways. 
provisioning action correlation ID: 1ffca0a2-64f7-47fb-a7f7-a923213a2511 !

**Comment by HiltonGiesenow** [comment]
I'm having a problem with the new employee onboarding (NEO) template, which I think is the same. In the email I get correlation ID: 7568b0b1-24a3-47c8-8848-e14b0524ba4b (using the provisioning website), but via PowerShell I get:

```Apply-PnPTenantTemplate : Access denied. You do not have permission to perform this action or access 
this resource.
```

Fyi, this is a brand-new test tenant (m365x.....sharepoint.com)

**Comment by PaoloPia** [comment]
Hi @phipham95,
Based on the event log, we can see - based on the provided Correlation ID - that you targeted an already existing site and the exception was "Forbidden". Could you please try to provision the solution to a different site URL? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by PaoloPia** [comment]
Hi @HiltonGiesenow,
Yes, based on the event log, it looks like you are experiencing exactly the same issue described here. We're working on it. We'll let you know. Unfortunately, it is a non-deterministic issue and the best thing to do is to retry targeting a different site URL. If it keeps on failing, I'm sorry but you can only wait for a fix to come out. Thanks for your comprehension.

**Comment by phipham95** [comment]
@PaoloPia Thanks I was able to update the existing Learning Pathways and got it to work.

**Comment by HiltonGiesenow** [comment]
@PaoloPia, I'm trying a few times, mostly in completely new M365 Demo tenants - there's absolutely nothing in there except OOB demo content, and trying to apply these templates.

I'm trying now again, once again with a totally new tenant, and with more verbose logging on:

Set-PnPTraceLog -On -LogFile c:\temp\pnptraceoutput3.txt -WriteToConsole -Level Information

Connect-PnPOnline https://M365x746390.sharepoint.com
Apply-PnPTenantTemplate -Path C:\Dev\GitHub\sp-dev-provisioning-templates\tenant\NEO\NEO.pnp -Verbose

I am doing a pre-consent, if that makes any difference?
https://login.microsoftonline.com/0afeaadd-2d49-4b97-953e-444ca3194daa/adminconsent?client_id=31359c7f-bd7e-475c-86db-fdb8c937548e

Here is the full, detailed log:

powershell.exe Information: 0 : 2021-01-12 20:24:52.3653	[OfficeDevPnP.Core]	[0]	[Information]	File NEO.pnp retrieved from folder 	0ms	
powershell.exe Information: 0 : 2021-01-12 20:24:52.5000	[OfficeDevPnP.Core]	[0]	[Information]	File NEO.pnp retrieved from folder 	0ms	
powershell.exe Information: 0 : 2021-01-12 20:24:54.4733	[OfficeDevPnP.Core]	[0]	[Information]	File NEO.xml retrieved from folder 	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:01.8731	[Provisioning]	[18]	[Information]	ProgressDelegate registered	1ms	6b10fb15-7108-4f9b-98cc-296265265541
powershell.exe Information: 0 : 2021-01-12 20:25:01.8740	[Provisioning]	[18]	[Information]	MessagesDelegate registered	2ms	6b10fb15-7108-4f9b-98cc-296265265541
powershell.exe Error: 0 : 2021-01-12 20:25:17.8668	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Cannot get site https://m365x746390.sharepoint.com/sites/NewEmployeePreOnboarding.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoNoSiteException
ServerErrorTraceCorrelationId: 52a0a09f-d0ce-0000-8a91-c1a0428885a4
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Error: 0 : 2021-01-12 20:25:18.4161	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Unknown Error
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.SharePoint.Client.UnknownError
ServerErrorTraceCorrelationId: 52a0a09f-e0f4-0000-8a91-c998ff212380
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:27.0426	[OfficeDevPnP.Core]	[0]	[Debug]	Starting to wait for site collection to be created	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:27.0485	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.000 | Attempt 1/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:27.3979	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.351 | Attempt 2/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:27.3989	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.352 | Waiting 15 seconds	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:42.7644	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:15.717 | Attempt 3/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:42.7685	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:15.721 | Waiting 15 seconds	0ms	
powershell.exe Information: 0 : 2021-01-12 20:25:58.1556	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:31.108 | Finished	0ms	
powershell.exe Error: 0 : 2021-01-12 20:26:03.2241	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Cannot get site https://m365x746390.sharepoint.com/sites/NewEmployeeSalesOnboarding.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoNoSiteException
ServerErrorTraceCorrelationId: 5da0a09f-c0e1-0000-8a91-c8359c33ea9d
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Error: 0 : 2021-01-12 20:26:03.6638	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Unknown Error
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.SharePoint.Client.UnknownError
ServerErrorTraceCorrelationId: 5ea0a09f-0001-0000-8a91-c175d6757174
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:11.8089	[OfficeDevPnP.Core]	[0]	[Debug]	Starting to wait for site collection to be created	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:11.8129	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.000 | Attempt 1/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:12.1661	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.353 | Attempt 2/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:12.1680	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.354 | Waiting 15 seconds	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:27.5357	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:15.722 | Attempt 3/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:27.5407	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:15.726 | Waiting 15 seconds	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:42.9122	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:31.099 | Finished	0ms	
powershell.exe Error: 0 : 2021-01-12 20:26:48.0851	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Cannot get site https://m365x746390.sharepoint.com/sites/NewEmployeeEngineeringOnboarding.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoNoSiteException
ServerErrorTraceCorrelationId: 68a0a09f-80d5-0000-8a91-c58bcf2682f3
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Error: 0 : 2021-01-12 20:26:48.5546	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Unknown Error
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.SharePoint.Client.UnknownError
ServerErrorTraceCorrelationId: 68a0a09f-a0f7-0000-8a91-cfd14fa67563
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:56.6279	[OfficeDevPnP.Core]	[0]	[Debug]	Starting to wait for site collection to be created	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:56.6319	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.000 | Attempt 1/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:56.9820	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.350 | Attempt 2/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:26:56.9859	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:00.353 | Waiting 15 seconds	0ms	
powershell.exe Information: 0 : 2021-01-12 20:27:12.3436	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:15.711 | Attempt 3/80	0ms	
powershell.exe Information: 0 : 2021-01-12 20:27:12.3456	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:15.713 | Waiting 15 seconds	0ms	
powershell.exe Information: 0 : 2021-01-12 20:27:27.7029	[OfficeDevPnP.Core]	[0]	[Debug]	Elapsed: 00:31.070 | Finished	0ms	
powershell.exe Information: 0 : 2021-01-12 20:27:46.5892	[Provisioning]	[18]	[Information]	ProgressDelegate registered	0ms	6b10fb15-7108-4f9b-98cc-296265265541
powershell.exe Information: 0 : 2021-01-12 20:27:46.5902	[Provisioning]	[18]	[Information]	MessagesDelegate registered	2ms	6b10fb15-7108-4f9b-98cc-296265265541
powershell.exe Warning: 0 : 2021-01-12 20:27:46.9528	[Provisioning]	[18]	[Information]	The source site from which the template was generated had a base template ID value of SITEPAGEPUBLISHING#0, while the current target site has a base template ID value of GROUP#0. This could cause potential issues while applying the template.	363ms	6b10fb15-7108-4f9b-98cc-296265265541
powershell.exe Error: 0 : 2021-01-12 20:27:51.2332	[OfficeDevPnP.Core]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
ServerErrorCode: -2147024891
ServerErrorTypeName: System.UnauthorizedAccessException
ServerErrorTraceCorrelationId: 78a0a09f-f03f-0000-8a91-c9511411c334
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	



Here is the full

**Comment by HiltonGiesenow** [comment]
I think the correlation id you need appears at the end? 78a0a09f-f03f-0000-8a91-c9511411c334

**Comment by shochdoerfer** [comment]
Install also fails for me. Correlation ID: 5d501ec9-0057-410f-8e56-e0e6c1b71333 - I used an admin account to trigger the deployment so that should not be a permission issue, I assume.

**Comment by PaoloPia** [comment]
Hi @HiltonGiesenow ,
but you are using PowerShell locally, not the Look Book site. Right? I assumed you were having issues with the Look Book site. If not, I can still help you - indeed - but maybe this is not the right place to be. Moreover, I cannot investigate the SharePoint Online logs, I can only see the Look Book logs. I also see that you get the following error message:

The source site from which the template was generated had a base template ID value of SITEPAGEPUBLISHING#0, while the current target site has a base template ID value of GROUP#0.

So it looks like you are using a wrong template for the target site. Could you please try to fix this error, and in case of any further problem create an issue in the https://github.com/pnp/pnpframework repo or in the https://github.com/pnp/powershell repo? Thanks.
